version: '3.7'

x-default: &default
  env_file:
    - .env
    - ../app/.env
  networks:
    - app-network
  environment:
    TZ: ${TIMEZONE}
x-app: &app
  <<: *default
  build:
    dockerfile: Dockerfile
  volumes:
    - ../app:/app/mysite.local

services:
#  nginx:
#    <<: *app
#    container_name: nginx
#    image: myapp/nginx
#    build:
#      context: ./nginx
#    ports:
#      - "81:80"
  php-fpm:
    <<: *app
    container_name: php-fpm
    image: myapp/php
    build:
      context: ./php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
#  php-cli:
#    <<: *app
#    container_name: php-cli
#    image: myapp/cli
#    build:
#      context: ./php-cli

#  database:
#    <<: *default
#    container_name: database
#    image: mysql:5.7
#    ports:
#      - ${DB_PORT}:3306
#    volumes:
#      - ./database:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#      MYSQL_USER: ${DB_USERNAME}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}

networks:
  app-network:
    driver: bridge